import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { Navbar } from "@/components/Navbar";
import { Rail } from "@/components/Rail";
import { Sidebar } from "@/components/Sidebar";
import { Statusbar } from "@/components/Statusbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} flex flex-col h-[100dvh]`}>
        {" "}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          <div className="grow flex">
            <Rail />
            <Sidebar />
            <main> {children}</main>
          </div>

          <Statusbar />
        </ThemeProvider>
      </body>
    </html>
  );
}
